// Listing detail → Shoot: Voice (shot with voice / voice-over separately + "made"),
// and "Shoot for" (Instagram / YouTube / Collab, planned + done). Runs the real board
// with firebase-sync stubbed, and checks what is saved and what the tile warns about.
import { chromium } from 'playwright';
import { readFileSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defaultStages } from '../track-assets/track-pipeline.js';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ST = defaultStages(), sid = k => ST.find(s => s.key === k).id, T = 't';
const L = [{ id: 'v1', tenantId: T, title: 'Villa', location: 'ECR', stageId: sid('shoot_done'), media: { photos: true, floorPlan: true }, photosLink: 'https://drive.google.com/x', createdAt: Date.now() - 1e8, updatedAt: Date.now(), stageChangedAt: Date.now() }];
const STUB = `window.__saved=[];window.trackFirebase={saveListing:async l=>{window.__saved.push(JSON.parse(JSON.stringify(l)))},getInventory:async()=>(window.__inv||[]),getPropertyInternalNotes:async()=>'',getListingHistory:async()=>[],saveHistory:async()=>{},savePipeline:async()=>{},patchLead:async()=>{},savePosting:async()=>{}};
window.trackAuth={login:async()=>{},logout:async()=>{},getTenantId:()=>'t'};
setTimeout(()=>{window.onTrackAuthChange({email:'a@x'},'t');window.applyTrackPipelineSnapshot(${JSON.stringify(ST)});window.applyListingsSnapshot(${JSON.stringify(L)});window.applyTrackLeadsSnapshot([]);window.applyPostingSnapshot([]);window.__ready=true},0);`;

const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 950 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.route('**/*', r => {
  const u = new URL(r.request().url());
  if (u.hostname !== 'track.local') return r.abort();
  if (u.pathname === '/track-assets/firebase-sync.js') return r.fulfill({ contentType: 'text/javascript', body: STUB });
  const f = join(ROOT, decodeURIComponent(u.pathname));
  return existsSync(f)
    ? r.fulfill({ contentType: { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' }[extname(f)] || 'application/octet-stream', body: readFileSync(f) })
    : r.fulfill({ status: 404, body: '' });
});
await p.goto('http://track.local/propertytrack.html');
await p.waitForFunction(() => window.__ready); await p.waitForTimeout(300);
await p.evaluate(() => openDetail('v1')); await p.waitForTimeout(200);

let fails = 0;
const ok = (l, c, d = '') => { if (!c) fails++; console.log((c ? '  ok  ' : '  FAIL ') + l + (c ? '' : ' — ' + d)); };
const last = () => p.evaluate(() => window.__saved[window.__saved.length - 1]);
const tile = () => p.$eval('.tk-card[data-id="v1"]', c => c.textContent);
const settle = () => p.waitForTimeout(150);

console.log('Voice');
ok('starts Not decided, no voice-over tick', await p.$eval('.tk-voice select', s => s.value) === '' && !(await p.$('label:has-text("Voice-over made")')));
await p.selectOption('.tk-voice select', 'vo'); await settle();
ok('Voice-over separately: saved, and "Voice-over made" appears', (await last()).voice === 'vo' && !!(await p.$('label:has-text("Voice-over made")')));
ok('…the tile says voice-over not made', /voice-over not made/.test(await tile()));
await p.check('label:has-text("Voice-over made") input'); await settle();
ok('ticking it saves and clears the tile warning', (await last()).voDone === true && !/voice-over not made/.test(await tile()));
await p.selectOption('.tk-voice select', 'live'); await settle();
ok('Shot with voice: the voice-over tick goes and is reset', (await last()).voice === 'live' && (await last()).voDone === false && !(await p.$('label:has-text("Voice-over made")')));

console.log('Shoot for');
const rows = await p.$$eval('#dpFor .tk-brief-r', r => r.map(x => x.textContent.trim()));
ok('lists Instagram, YouTube, Collab', rows.length === 3 && /Instagram/.test(rows[0]) && /YouTube/.test(rows[1]) && /Collab/.test(rows[2]), JSON.stringify(rows));
await p.check('#dpFor input[aria-label="Instagram planned"]'); await settle();
await p.check('#dpFor input[aria-label="YouTube planned"]'); await settle();
const s = await last();
ok('several can be planned at once', s.forPlan.insta && s.forPlan.yt && !s.forPlan.collab);
ok('…the tile says what is still to make', /Instagram \+ YouTube not done/.test(await tile()));
await p.check('#dpFor input[aria-label="Instagram done"]'); await settle();
ok('Done ticks; the tile narrows to what is left', (await last()).forDone.insta && /YouTube not done/.test(await tile()) && !/Instagram/.test(await p.$eval('.tk-card[data-id="v1"] .tk-blockers', c => c.textContent)));
await p.check('#dpFor input[aria-label="Collab done"]'); await settle();
ok('ticking Done on something not planned plans it too', (await last()).forPlan.collab && (await last()).forDone.collab);
await p.uncheck('#dpFor input[aria-label="YouTube planned"]'); await settle();
const blk = () => p.$eval('.tk-card[data-id="v1"] .tk-blockers', c => c.textContent).catch(() => '');
ok('un-planning clears its Done and its warning — only the brochure is left', !(await last()).forPlan.yt && !(await last()).forDone.yt && (await blk()).trim() === 'no brochure', await blk());

console.log('Media ready');
const stageOf = () => p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v1').stageId);
const colOf = () => p.$eval('.tk-card[data-id="v1"]', c => c.closest('.tk-col').querySelector('.tk-col-title').textContent);
ok('the column sits between Shoot done and Live', (await p.$$eval('.tk-col-title', t => t.map(e => e.textContent))).join('|').includes('Shoot done|Media ready|Live'));
ok('with the brochure still missing, the listing stays in Shoot done', await stageOf() === 'shoot_done');
await p.evaluate(() => window.trackApi.mutate('v1', x => { x.brochure = { ...(x.brochure || {}), doneAt: Date.now() }; }, 'Brochure created')); await settle();
ok('the brochure was the last thing → it moves to Media ready by itself', await stageOf() === 'media_ready' && await colOf() === 'Media ready', await stageOf());
ok('…said in a toast and in its history', /Media ready/.test(await p.$eval('#toast', t => t.textContent).catch(() => '')) && /automatically, everything the shoot was for is done/.test((await last()).lastEvent.text), (await last()).lastEvent.text);
ok('…with no warnings on the tile', !(await blk()));
await p.evaluate(() => setMedia('v1', 'floorPlan', false)); await settle();
ok('unticking something later keeps it in Media ready, and the tile says what went missing', await stageOf() === 'media_ready' && /1 of 2 media missing/.test(await blk()), await blk());
await p.evaluate(() => setMedia('v1', 'floorPlan', true)); await settle();
ok('…ticked again, the warning goes', await stageOf() === 'media_ready' && !(await blk()));
await p.evaluate(() => changeStage('v1', 'shoot_done')); await settle();
await p.evaluate(() => window.applyListingsSnapshot(window.trackApi.listings())); await settle();
ok('moved back to Shoot done by hand, it stays there (no bouncing back)', await stageOf() === 'shoot_done');
await p.evaluate(() => window.trackApi.mutate('v1', x => { x.remarks = 'reshoot the balcony'; }, 'Remarks edited')); await settle();
ok('…a note or remark on it does not send it forward again', await stageOf() === 'shoot_done');
await p.evaluate(() => setMedia('v1', 'floorPlan', false)); await settle();
await p.evaluate(() => setMedia('v1', 'floorPlan', true)); await settle();
ok('…finishing the last missing piece again does move it on', await stageOf() === 'media_ready');
const saved1 = await last();
ok('the milestone is saved as reached.media_ready (a nested date, not a dotted field name)', typeof (saved1.reached || {}).media_ready === 'number' && !Object.keys(saved1).some(k => k.startsWith('reached.')), JSON.stringify(Object.keys(saved1)));
await p.evaluate(() => { changeStage('v1', 'shoot_scheduled'); }); await settle();
await p.evaluate(() => { changeStage('v1', 'shoot_done'); }); await settle();
ok('brought forward into Shoot done with everything in hand → straight on to Media ready', await stageOf() === 'media_ready');
await p.evaluate(() => { changeStage('v1', 'shoot_done'); window.trackApi.mutate('v1', x => { x.brochure = { ...x.brochure, doneAt: null, unlockedAt: Date.now(), unlockedLink: '' }; }, 'Brochure details unlocked for a redo'); }); await settle();
ok('a brochure unlocked for a redo no longer counts: no ✓ on the tile, and it is not promoted', await stageOf() === 'shoot_done' && !/Brochure ✓/.test(await tile()) && /no brochure/.test(await blk()), await tile());
await p.evaluate(() => window.trackApi.mutate('v1', x => { x.brochure = { ...x.brochure, doneAt: Date.now() }; }, 'Brochure created')); await settle();
ok('…redone, it counts again and the listing moves on', await stageOf() === 'media_ready' && /Brochure ✓/.test(await tile()));
await p.evaluate(() => { changeStage('v1', 'shoot_done'); setMedia('v1', 'photos', false); changeStage('v1', 'media_ready'); }); await settle();
ok('moved into Media ready by hand with gaps: allowed, and the toast says what is missing', await stageOf() === 'media_ready' && /still missing: 1 of 2 media missing/.test(await p.$eval('#toast', t => t.textContent)), await p.$eval('#toast', t => t.textContent));

console.log('The brochure arriving from the pipeline');
const R = { id: 'v3', tenantId: T, title: 'Linked flat', stageId: 'shoot_done', propertyCode: 'EGM0001', media: { photos: true, floorPlan: true }, photosLink: 'https://drive.google.com/z', brochure: { code: 'EGM0001', requestedAt: Date.now() - 3600000, requestedCode: 'EGM0001' }, createdAt: 1, updatedAt: 1, stageChangedAt: 1 };
await p.evaluate(r => { window.__inv = [{ id: 'EGM0001', propertyCode: 'EGM0001', name: 'Egmore 3BHK', brochureLink: '' }]; window.applyListingsSnapshot([...window.trackApi.listings(), r]); }, R); await settle();
const v3 = () => p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v3'));
ok('brochure requested, not delivered: waits in Shoot done', (await v3()).stageId === 'shoot_done');
await p.evaluate(() => { window.__inv = [{ id: 'EGM0001', propertyCode: 'EGM0001', name: 'Egmore 3BHK', brochureLink: 'https://drive.google.com/file/d/egm' }]; window.bpReconcile(true); }); await p.waitForTimeout(500);
ok('delivered (the usual last piece): ticked done AND moved to Media ready by itself', !!(await v3()).brochure.doneAt && (await v3()).stageId === 'media_ready', JSON.stringify((await v3()).stageId));
await p.evaluate(() => changeStage('v3', 'on_hold', { reason: 'owner_postponed' })); await settle();
await p.evaluate(() => changeStage('v3', 'shoot_done')); await settle();
ok('back from On hold into Shoot done with everything in hand: moves on to Media ready', (await v3()).stageId === 'media_ready');
await p.evaluate(() => changeStage('v3', 'shoot_done')); await settle();
ok('moved back by hand from Media ready: held in Shoot done', (await v3()).stageId === 'shoot_done' && (await v3()).heldBack === true);
await p.evaluate(() => window.bpReconcile(true)); await p.waitForTimeout(400);
await p.evaluate(() => window.trackApi.mutate('v3', x => { x.remarks = 'second look'; })); await settle();
ok('…a reconcile or a remark does not release it', (await v3()).stageId === 'shoot_done');
await p.evaluate(() => window.trackApi.mutate('v3', x => { x.brochure = { ...x.brochure, doneAt: null, unlockedAt: Date.now(), unlockedLink: 'https://drive.google.com/file/d/egm' }; }, 'Brochure details unlocked for a redo')); await settle();
await p.evaluate(() => window.trackApi.mutate('v3', x => { x.brochure = { ...x.brochure, requestedAt: Date.now(), requestedCode: 'EGM0001' }; }, 'Brochure requested')); await settle();
ok('held, brochure unlocked and asked for again: still waits', (await v3()).stageId === 'shoot_done');
await p.evaluate(() => { window.__inv = [{ id: 'EGM0001', propertyCode: 'EGM0001', name: 'Egmore 3BHK', brochureLink: 'https://drive.google.com/file/d/egm-v2' }]; window.bpReconcile(true); }); await p.waitForTimeout(500);
ok('…the new brochure arriving (the last missing piece) releases it to Media ready', (await v3()).stageId === 'media_ready' && !(await v3()).heldBack, JSON.stringify({ s: (await v3()).stageId, h: (await v3()).heldBack, d: (await v3()).brochure.doneAt }));
await p.evaluate(() => changeStage('v3', 'shoot_done')); await settle();
await p.evaluate(() => { openEditModal('v3'); document.getElementById('mm_propertyCode').value = ''; saveModal(); }); await p.waitForTimeout(400);
const un = await v3();
ok('unlinked in Edit: the old property\'s brochure goes with it (no ✓, link cleared, not locked)', !un.propertyCode && !un.brochure.doneAt && !un.brochureLink && !/Brochure ✓/.test(await p.$eval('.tk-card[data-id="v3"]', c => c.textContent)), JSON.stringify({ pc: un.propertyCode, b: un.brochure, bl: un.brochureLink }));

const U = { id: 'v4', tenantId: T, title: 'Unmap me', stageId: 'details', propertyCode: 'EGM0001', brochureLink: 'https://drive.google.com/file/d/egm-v2', brochure: { code: 'EGM0001', requestedAt: Date.now() - 60000, requestedCode: 'EGM0001', doneAt: Date.now() }, createdAt: 1, updatedAt: 1, stageChangedAt: 1 };
await p.evaluate(u => window.applyListingsSnapshot([...window.trackApi.listings(), u]), U); await settle();
await p.evaluate(() => { openMapProperty('v4'); pickProperty(''); }); await settle();
await p.evaluate(() => window.bpReconcile(true)); await p.waitForTimeout(500);
const v4 = await p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v4'));
ok('"✕ Unmap" stays unmapped (the background check does not link it back) and drops the old brochure', !v4.propertyCode && !v4.brochure.doneAt && !v4.brochure.requestedAt && !v4.brochureLink, JSON.stringify(v4.brochure));

console.log('Who goes on the shoot — the team');
await p.evaluate(() => window.applyTrackTeamSnapshot({ k1: { email: 'swami@threepin.in' }, k2: { email: 'pradeep.kumar@threepin.in' }, k3: { email: 'not-an-email' }, k4: { email: 'sales@threepin.in' }, k5: { email: 'admin@threepin.in' } }));
const S = { id: 'v5', tenantId: T, title: 'Shoot me', stageId: 'details', media: {}, shootAssignee: 'Rajesh', createdAt: 1, updatedAt: 1, stageChangedAt: 1 };
await p.evaluate(s => window.applyListingsSnapshot([...window.trackApi.listings(), s]), S); await settle();
await p.evaluate(() => openDetail('v5')); await settle();
const opts = await p.$$eval('select[aria-label="Shoot assigned to"] option, select[aria-label="Shoot assigned to"] optgroup', o => o.map(e => e.tagName === 'OPTGROUP' ? '[' + e.label + ']' : e.textContent));
ok('Assigned to is a dropdown: the media team (named like the CRM; no sales@/admin@ mailboxes), others sent before, someone else', JSON.stringify(opts) === JSON.stringify(['Not assigned', '[Media team]', 'Pradeep Kumar', 'Swami', '[Also sent before]', 'Rajesh', 'Someone else…']), JSON.stringify(opts));
await p.selectOption('select[aria-label="Shoot assigned to"]', 'Swami'); await settle();
const v5 = () => p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v5'));
ok('picking a teammate saves the name and their email', (await v5()).shootAssignee === 'Swami' && (await v5()).shootAssigneeEmail === 'swami@threepin.in', JSON.stringify(await v5()));
p.once('dialog', d => d.accept('Kumar Studio'));
await p.selectOption('select[aria-label="Shoot assigned to"]', '__other'); await settle();
ok('"Someone else…" asks for a name and keeps it (no email)', (await v5()).shootAssignee === 'Kumar Studio' && !(await v5()).shootAssigneeEmail);
p.once('dialog', d => d.dismiss());
await p.selectOption('select[aria-label="Shoot assigned to"]', '__other'); await settle();
ok('…cancelling it changes nothing', (await v5()).shootAssignee === 'Kumar Studio' && await p.$eval('select[aria-label="Shoot assigned to"]', s => s.value) === 'Kumar Studio');
await p.evaluate(() => { document.getElementById('dp').classList.remove('open'); }); await settle();
await p.evaluate(() => document.querySelector('.tk-card[data-id="v5"] button.tk-link[onclick*="openShootModal"]').click()); await settle();
ok('a tile with no shoot has "Book →", which opens the booking', await p.evaluate(() => document.getElementById('shModal').classList.contains('open')));
const shOpts = await p.$$eval('#shWho option', o => o.map(e => e.textContent));
ok('the booking\'s Assigned to is the same dropdown, current choice selected', shOpts.includes('Swami') && shOpts.includes('Pradeep Kumar') && await p.$eval('#shWho', s => s.value) === 'Kumar Studio', JSON.stringify(shOpts));
await p.evaluate(() => { document.getElementById('shDate').value = '2026-10-20'; document.getElementById('shTime').value = '11:30'; });
await p.selectOption('#shWho', 'Pradeep Kumar');
await p.evaluate(() => saveShoot()); await settle();
const b5 = await v5();
ok('booked: date, teammate + email saved, and the card moved to Shoot scheduled', b5.shootAt === new Date('2026-10-20T11:30').getTime() && b5.shootAssignee === 'Pradeep Kumar' && b5.shootAssigneeEmail === 'pradeep.kumar@threepin.in' && b5.stageId === 'shoot_scheduled', JSON.stringify({ at: b5.shootAt, w: b5.shootAssignee, s: b5.stageId }));
const S6 = { id: 'v6', tenantId: T, title: 'Dragged', stageId: 'details', media: {}, createdAt: 1, updatedAt: 1, stageChangedAt: 1 };
await p.evaluate(s => window.applyListingsSnapshot([...window.trackApi.listings(), s]), S6); await settle();
await p.evaluate(() => { closeShootModal(); changeStage('v6', 'shoot_scheduled'); }); await settle();
ok('moved into Shoot scheduled with no date: the booking opens to pick it', await p.evaluate(() => document.getElementById('shModal').classList.contains('open')));
await p.evaluate(() => closeShootModal());
await p.evaluate(() => openEditModal('v5')); await settle();
ok('the Edit form\'s "Shoot assigned to" is the same dropdown', await p.$eval('#mm_shootAssignee', s => s.tagName === 'SELECT' && s.value === 'Pradeep Kumar'));
await p.evaluate(() => closeModal());
// An older listing spelled in lower case is the same person — on the shoot phone and in the pickers.
const S7 = { id: 'v7', tenantId: T, title: 'Lower case', stageId: 'shoot_scheduled', media: {}, shootAt: Date.now() + 86400000, shootAssignee: 'swami', shootAssigneeEmail: 'swami@threepin.in', createdAt: 1, updatedAt: 1, stageChangedAt: 1 };
await p.evaluate(s => window.applyListingsSnapshot([...window.trackApi.listings(), s]), S7); await settle();
await p.evaluate(() => { toggleView('shoots'); setAgentFilter('Swami'); }); await settle();
ok('"Whose day: Swami" includes a shoot saved as "swami"', /Lower case/.test(await p.$eval('#shootsView', e => e.textContent)));
await p.evaluate(s => window.applyListingsSnapshot([...window.trackApi.listings(), s]), { id: 'v8', tenantId: T, title: 'Old spelling', stageId: 'shoot_scheduled', media: {}, shootAt: Date.now() + 2 * 86400000, shootAssignee: 'Swaminathan', shootAssigneeEmail: 'swami@threepin.in', createdAt: 1, updatedAt: 1, stageChangedAt: 1 }); await settle();
await p.evaluate(() => setAgentFilter('Swami')); await settle();
ok('…and a shoot of theirs under another spelling, matched by their email', /Old spelling/.test(await p.$eval('#shootsView', e => e.textContent)));
ok('…with no separate button for that spelling', !(await p.$$eval('.tk-agentbar .tk-sbtn', b => b.map(e => e.textContent.trim()))).includes('Swaminathan'));
const whose = await p.$$eval('.tk-agentbar .tk-sbtn', b => b.map(e => e.textContent.trim()));
ok('"Whose day" lists people with shoots, not every teammate', !whose.includes('Pradeep Kumar') || whose.length <= 4, JSON.stringify(whose));
ok('…one button per person, whatever the spelling', whose.filter(w => /^swami$/i.test(w)).length === 1, JSON.stringify(whose));
await p.evaluate(() => { setAgentFilter(''); toggleView('board'); openDetail('v7'); }); await settle();
p.once('dialog', d => d.dismiss());
await p.selectOption('select[aria-label="Shoot assigned to"]', '__other'); await settle();
ok('cancelling "Someone else…" on a lower-case name puts the choice back (not blank)', await p.$eval('select[aria-label="Shoot assigned to"]', s => s.value) === 'Swami');
p.once('dialog', d => d.accept('SWAMI'));
await p.selectOption('select[aria-label="Shoot assigned to"]', '__other'); await settle();
const v7 = await p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v7'));
ok('typing an existing name under "Someone else…" picks that person (no second spelling)', v7.shootAssignee === 'Swami' && v7.shootAssigneeEmail === 'swami@threepin.in' && await p.$$eval('select[aria-label="Shoot assigned to"] option', o => o.filter(e => /^swami$/i.test(e.value)).length) === 1, JSON.stringify(v7));
await p.fill('#dpNoteText', 'half typed note');
await p.focus('#dpNoteText');
await p.evaluate(() => window.applyTrackTeamSnapshot({ x2: { email: 'pradeep.kumar@threepin.in' }, x1: { email: 'swami@threepin.in' } })); await settle();
ok('a settings change that is not a team change disturbs nothing (focus stays in the note)', await p.evaluate(() => document.activeElement && document.activeElement.id === 'dpNoteText'));
await p.evaluate(() => { document.getElementById('dpNoteText').value = ''; document.getElementById('dp').classList.remove('open'); window.applyTrackTeamSnapshot({}); }); await settle();
await p.evaluate(() => { openShootModal('v7'); saveShoot(); }); await settle();
ok('team not loaded: saving the same person keeps their email', (await p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v7').shootAssigneeEmail)) === 'swami@threepin.in');
await p.evaluate(() => window.applyTrackTeamSnapshot({ k1: { email: 'swami@threepin.in' }, k2: { email: 'pradeep.kumar@threepin.in' } }));
// Edit form on a listing whose shooter is stored in another spelling: saving anything keeps them.
await p.evaluate(() => window.trackApi.mutate('v7', x => { x.shootAssignee = 'rajesh '; x.shootAssigneeEmail = null; })); await settle();
await p.evaluate(() => { closeDetail(); openEditModal('v7'); }); await settle();
const picked = await p.$eval('#mm_shootAssignee', s => s.value);
ok('Edit form shows a stored "rajesh " as chosen (not blank)', picked.trim().toLowerCase() === 'rajesh', JSON.stringify(picked));
await p.fill('#mm_askingPrice', '₹95 L');
await p.evaluate(() => saveModal()); await settle();
const kept = await p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v7'));
ok('…and saving a price change keeps the shooter', kept.shootAssignee.trim().toLowerCase() === 'rajesh' && kept.askingPrice === '₹95 L', JSON.stringify({ w: kept.shootAssignee, p: kept.askingPrice }));
await p.evaluate(() => { closeShootModal(); closeDetail(); });
await p.evaluate(() => document.querySelector('.tk-card[data-id="v6"] button.tk-link[onclick*="openShootModal"]')?.focus());
await p.keyboard.press('Enter'); await settle();
ok('Enter on a tile\'s "Book →" opens the booking, not the listing', await p.evaluate(() => document.getElementById('shModal').classList.contains('open') && !document.getElementById('dp').classList.contains('open')));
await p.evaluate(() => closeShootModal());

console.log('An existing board');
const OLD = ST.filter(s => s.key !== 'media_ready').map((s, i) => ({ ...s, order: i }));
const DONE = { id: 'v2', tenantId: T, title: 'Ready flat', stageId: 'shoot_done', media: { photos: true, floorPlan: true }, photosLink: 'https://drive.google.com/y', brochure: { doneAt: Date.now() }, createdAt: 1, updatedAt: 1, stageChangedAt: 1 };
await p.evaluate(d => window.applyListingsSnapshot([...window.trackApi.listings(), d]), DONE); await settle();
ok('a complete listing arriving by snapshot is not moved by this tab (whoever changed it did that)', await p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v2').stageId) === 'shoot_done');
await p.evaluate(old => { window.__pipes = []; window.trackFirebase.savePipeline = async s => { window.__pipes.push(s); }; window.applyTrackPipelineSnapshot(old); }, OLD); await settle();
const saved = await p.evaluate(() => window.__pipes[0]);
ok('a board saved without Media ready gains it after Shoot done, and is saved once', saved && saved.map(s => s.name).join('|').includes('Shoot done|Media ready|Live') && saved.every((s, i) => s.order === i), JSON.stringify(saved && saved.map(s => s.name)));
await p.evaluate(s => window.applyTrackPipelineSnapshot(s), saved); await settle();
ok('…and a board that has it is not saved again', await p.evaluate(() => window.__pipes.length) === 1);
ok('when the column is added, listings already complete in Shoot done move into it once', await p.evaluate(() => window.trackApi.listings().find(l => l.id === 'v2').stageId) === 'media_ready');

ok('no page errors', !errs.length, errs.join(' | '));
await b.close();
if (fails) { console.log(`\n${fails} failed`); process.exit(1); }
console.log('\nAll shoot-extras checks passed');
